### PR TITLE
Error should be thrown, not returned

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by drazisil** [comment]
@teohhanhui Thank you. Can you update the tests to match, please?

**Comment by drazisil** [comment]
Closing as stale

**Comment by teohhanhui** [comment]
Was this fixed?

**Comment by drazisil** [comment]
No, I was waiting for you to update the tests, I can't merge it while it's failing.

**Comment by teohhanhui** [comment]
Yes, I'm aware of that. Sorry that I wasn't able to work on this. But the problem is still valid.

**Comment by drazisil** [comment]
Ok, I'll leave it open.

**Comment by drazisil** [comment]
Closing as I no longer update this repo

**Pull request closed without merging**
