### PR TITLE
Recursively Get Xml Files from a Directory

### PR DESCRIPTION
**Pull request by 5punk**

### CODE REVIEW

**Comment by 5punk** [comment]
you are welcome

**Comment by drazisil** [comment]
@5punk That didn't pass tests, can you correct?

**Comment by 5punk** [comment]
It passed all unit tests.
I ran `npm test`, am I missing something?

**Comment by 5punk** [comment]
Also, can you publish/release.
We are excited to use this new functionality

**Comment by drazisil** [comment]
@5punk Sorry, the failure was on me. Published as 1.2.0, thank you https://www.npmjs.com/package/junit-merge

**Comment by 5punk** [comment]
Thanks mate.

**Pull request merged**
