### PR TITLE
use strict to alow node 4 executions

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Hi there,

Thank you for this great tool :)
I would like to use this CLI on a node 4 environment, therefore I need the use strict statement as block scoped variables (let or const) are not allowed without use strict there

### CODE REVIEW

**Comment by DanielMSchmidt** [comment]
Thank you for merging this @drazisil Could you ping me when you are done with releasing this? Thank you 👍

**Comment by drazisil** [comment]
@DanielMSchmidt Yep, will do. Just need to find a way to run tests on it, looks like Jest doesn't support Node 4.

**Comment by DanielMSchmidt** [comment]
That's a bummer. Sorry that I come along with these legacy issues

**Comment by drazisil** [comment]
No worries at all. I'll get it sorted :)

**Comment by drazisil** [comment]
@DanielMSchmidt Here you go. https://github.com/drazisil/junit-merge/releases/tag/v1.2.4

Thanks again! :)

**Pull request merged**
